try:
    10/0
except Exception as e:
    print("Ocurrio un error", e)
    
print("continuemos ...")